language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - |
    if [ "$(phpenv version-name)" != 8.0 ]; then
      echo -n "PHP version="; phpenv version-name
      phpenv config-rm xdebug.ini
    fi

install:
  - composer validate --strict
  - composer install

before_script:
  - mkdir -p .build/php-cs-fixer
  - php -m

script:
  - ./generate.sh
  - php -l acf-pro-stubs.php
  - php -r "require './vendor/php-stubs/wordpress-stubs/wordpress-stubs.php'; require 'acf-pro-stubs.php';"
  - git diff --exit-code

notifications:
  email: false
